name = "shop"
account_id = "dedf79626ca47685dc9bc5194f2c1b2f"
compatibility_date = "2025-11-04"
pages_build_output_dir = ".open-next/worker"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
