name = "shop-interact"
main = ".open-next/worker.js"
account_id = "dedf79626ca47685dc9bc5194f2c1b2f"
compatibility_date = "2025-11-04"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
