name = "interact"
account_id = "dedf79626ca47685dc9bc5194f2c1b2f"
compatibility_date = "2025-11-04"
workers_dev = true

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[assets]
directory = "./out"
