name = "interact"      
type = "javascript"            
account_id = "dedf79626ca47685dc9bc5194f2c1b2f" 
workers_dev = true
compatibility_date = "2025-11-04"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[site]
bucket = ".next"
entry-point = "workers-site"
